#!/usr/bin/env bash

# Generated by Noctalia user templates. Do not edit by hand.

export WVKBD_ALPHA="255"
export WVKBD_BG="{{colors.surface.default.hex_stripped}}"
export WVKBD_FG="{{colors.surface_container.default.hex_stripped}}"
export WVKBD_FG_SP="{{colors.secondary_container.default.hex_stripped}}"
export WVKBD_PRESS="{{colors.primary.default.hex_stripped}}"
export WVKBD_PRESS_SP="{{colors.secondary.default.hex_stripped}}"
export WVKBD_SWIPE="{{colors.tertiary.default.hex_stripped}}"
export WVKBD_SWIPE_SP="{{colors.tertiary_container.default.hex_stripped}}"
export WVKBD_TEXT="{{colors.on_surface.default.hex_stripped}}"
export WVKBD_TEXT_SP="{{colors.on_secondary_container.default.hex_stripped}}"
